"""add role to users

Revision ID: e02650d6956f
Revises: d1648f3275f8
Create Date: 2025-12-31 17:05:43.178962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02650d6956f'
down_revision: Union[str, Sequence[str], None] = 'd1648f3275f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add role column with server default for existing rows
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # Remove server default (model handles default now)
    op.alter_column('users', 'role', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
